// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: demo1

#ifndef _UI_COMP_GEARNUMBER_H
#define _UI_COMP_GEARNUMBER_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT GearNumber
#define UI_COMP_GEARNUMBER_GEARNUMBER 0
#define _UI_COMP_GEARNUMBER_NUM 1
lv_obj_t * ui_GearNumber_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
