// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: ElecrowScreen

#include "ui.h"
#include "config.h"
// const uint16_t RPM_DISPLAY_MIN = 0;     // Minimum RPM value that can be shown on the slider.
// const uint16_t RPM_DISPLAY_MAX = 900;   // Maximum RPM value that can be shown on the slider.
const float OLD_RANGE = RPM_DISPLAY_MAX - RPM_DISPLAY_MIN;
const float NEW_RANGE = 800;
const float MULTIPLIER = NEW_RANGE / OLD_RANGE;
const int OFFSET = 400;

const int greenWidth = (RPM_MAX - RPM_MIN) * MULTIPLIER;
const int greenX = (MULTIPLIER * RPM_MIN) + (greenWidth/2) - OFFSET;

const int blueWidth = (RPM_MIN - RPM_DISPLAY_MIN) * MULTIPLIER;
const int blueX = (MULTIPLIER * RPM_DISPLAY_MIN) + (blueWidth/2) - OFFSET;

const int redWidth = (RPM_DISPLAY_MAX - RPM_MAX) * MULTIPLIER;
const int redX = (MULTIPLIER * RPM_MAX) + (redWidth/2) - OFFSET;

const int y_value = (BAR_HEIGHT / 2) - 240;
const int bar_ratio = 0.8;

// const uint16_t MID_RANGE = RANGE / 2 - 400;

// //message Ethan or David to get the red and blue to line up with shifting.
// const uint16_t RPM_MIN = 225;     // Starts flashing when RPM drops *below* this value (shift down).
// const uint16_t RPM_MAX = 675;     // Starts flashing when RPM exceeds *above* this value (shift up).

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rpmbackgreen = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_rpmbackgreen, greenWidth);//400
    lv_obj_set_height(ui_rpmbackgreen, BAR_HEIGHT);
    lv_obj_set_x(ui_rpmbackgreen, greenX); //0
    lv_obj_set_y(ui_rpmbackgreen, y_value);
    lv_obj_set_align(ui_rpmbackgreen, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_rpmbackgreen, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmbackgreen, lv_color_hex(0x00FF36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmbackgreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmbackblue = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_rpmbackblue, blueWidth);//200
    lv_obj_set_height(ui_rpmbackblue, BAR_HEIGHT);
    lv_obj_set_x(ui_rpmbackblue, blueX);//-300
    lv_obj_set_y(ui_rpmbackblue, y_value);
    lv_obj_set_align(ui_rpmbackblue, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_rpmbackblue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmbackblue, lv_color_hex(0x1100F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmbackblue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmbackred = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_rpmbackred, redWidth); //200
    lv_obj_set_height(ui_rpmbackred, BAR_HEIGHT);
    lv_obj_set_x(ui_rpmbackred, redX);//300
    lv_obj_set_y(ui_rpmbackred, y_value);
    lv_obj_set_align(ui_rpmbackred, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_rpmbackred, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmbackred, lv_color_hex(0xF60000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmbackred, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_erpmbackswitchup = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_erpmbackswitchup, 400);
    lv_obj_set_height(ui_erpmbackswitchup, BAR_HEIGHT);
    lv_obj_set_x(ui_erpmbackswitchup, 200);
    lv_obj_set_y(ui_erpmbackswitchup, y_value);
    lv_obj_set_align(ui_erpmbackswitchup, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_erpmbackswitchup, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_erpmbackswitchup, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_bg_color(ui_erpmbackswitchup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);//0xFCFF00
    lv_obj_set_style_bg_opa(ui_erpmbackswitchup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_erpmbackswitchdown = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_erpmbackswitchdown, 400);
    lv_obj_set_height(ui_erpmbackswitchdown, BAR_HEIGHT);
    lv_obj_set_x(ui_erpmbackswitchdown, -200);
    lv_obj_set_y(ui_erpmbackswitchdown, y_value);
    lv_obj_set_align(ui_erpmbackswitchdown, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_erpmbackswitchdown, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_flag(ui_erpmbackswitchdown, LV_OBJ_FLAG_HIDDEN);
    lv_obj_set_style_bg_color(ui_erpmbackswitchdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_erpmbackswitchdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_erpmbar = lv_bar_create(ui_Screen1);
    lv_bar_set_range(ui_erpmbar, RPM_DISPLAY_MIN, RPM_DISPLAY_MAX);
    lv_bar_set_value(ui_erpmbar, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_erpmbar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_erpmbar, 800);
    lv_obj_set_height(ui_erpmbar, BAR_HEIGHT * bar_ratio);
    lv_obj_set_x(ui_erpmbar, 0);
    lv_obj_set_y(ui_erpmbar, y_value);
    lv_obj_set_align(ui_erpmbar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_erpmbar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_erpmbar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_erpmbar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_erpmbar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_rpmtextback = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_rpmtextback, 250);
    lv_obj_set_height(ui_rpmtextback, 30);
    lv_obj_set_x(ui_rpmtextback, -10);
    lv_obj_set_y(ui_rpmtextback, 35);
    lv_obj_set_align(ui_rpmtextback, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_rpmtextback, lv_color_hex(0x00FF36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmtextback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmfrontgreen = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_rpmfrontgreen, greenWidth);//400
    lv_obj_set_height(ui_rpmfrontgreen, BAR_HEIGHT);
    lv_obj_set_x(ui_rpmfrontgreen, greenX);//0
    lv_obj_set_y(ui_rpmfrontgreen, y_value);
    lv_obj_set_align(ui_rpmfrontgreen, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_rpmfrontgreen, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmfrontgreen, lv_color_hex(0x00FF36), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmfrontgreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmfrontblue = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_rpmfrontblue, blueWidth); //200
    lv_obj_set_height(ui_rpmfrontblue, BAR_HEIGHT);
    lv_obj_set_x(ui_rpmfrontblue, blueX);//-300
    lv_obj_set_y(ui_rpmfrontblue, y_value);
    lv_obj_set_align(ui_rpmfrontblue, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_rpmfrontblue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmfrontblue, lv_color_hex(0x1100F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmfrontblue, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmfrontred = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_rpmfrontred, redWidth); //200
    lv_obj_set_height(ui_rpmfrontred, BAR_HEIGHT);
    lv_obj_set_x(ui_rpmfrontred, redX);//300
    lv_obj_set_y(ui_rpmfrontred, y_value);
    lv_obj_set_align(ui_rpmfrontred, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_rpmfrontred, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rpmfrontred, lv_color_hex(0xF60000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rpmfrontred, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rpmdu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_rpmdu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_rpmdu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_rpmdu, -70);
    lv_obj_set_y(ui_rpmdu, 25);
    lv_obj_set_align(ui_rpmdu, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_rpmdu, "RPM");
    lv_obj_set_style_text_color(ui_rpmdu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rpmdu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rpmdu, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_erpm = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_erpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_erpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_erpm, 60);
    lv_obj_set_y(ui_erpm, 25);
    lv_obj_set_align(ui_erpm, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_erpm, "U");
    lv_obj_set_style_text_color(ui_erpm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_erpm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_erpm, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    
    ui_geardu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_geardu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_geardu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_geardu, 0);
    lv_obj_set_y(ui_geardu, -40);
    lv_obj_set_align(ui_geardu, LV_ALIGN_CENTER);
    lv_label_set_text(ui_geardu, "Gear");
    lv_obj_set_style_text_font(ui_geardu, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_egear = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_egear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_egear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_egear, 0);
    lv_obj_set_y(ui_egear, 90);
    lv_obj_set_align(ui_egear, LV_ALIGN_CENTER);
    lv_label_set_text(ui_egear, "5");
    lv_obj_set_style_text_font(ui_egear, &ui_font_Font250, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_evoltageback = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_evoltageback, 200);
    lv_obj_set_height(ui_evoltageback, 60);
    lv_obj_set_align(ui_evoltageback, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_evoltageback, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_evoltageback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_voltagedu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_voltagedu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_voltagedu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_voltagedu, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_voltagedu, "Batt           Volt");
    lv_obj_set_style_text_align(ui_voltagedu, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_voltagedu, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_evoltage = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_evoltage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_evoltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_evoltage, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_evoltage, "1234");
    lv_obj_set_style_text_align(ui_evoltage, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_evoltage, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eoiltemperatureback = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_eoiltemperatureback, 200);
    lv_obj_set_height(ui_eoiltemperatureback, 60);
    lv_obj_set_x(ui_eoiltemperatureback, 14);
    lv_obj_set_y(ui_eoiltemperatureback, 154);
    lv_obj_set_align(ui_eoiltemperatureback, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_eoiltemperatureback, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_eoiltemperatureback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oiltemperaturedu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_oiltemperaturedu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oiltemperaturedu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oiltemperaturedu, 0);
    lv_obj_set_y(ui_oiltemperaturedu, 90);
    lv_obj_set_align(ui_oiltemperaturedu, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_oiltemperaturedu, "Temp Deg");
    lv_obj_set_style_text_font(ui_oiltemperaturedu, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eoiltemperature = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_eoiltemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_eoiltemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_eoiltemperature, 50);
    lv_obj_set_y(ui_eoiltemperature, 150);
    lv_obj_set_align(ui_eoiltemperature, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_eoiltemperature, "1234");
    lv_obj_set_style_text_font(ui_eoiltemperature, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eoilpressureback = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_eoilpressureback, 200);
    lv_obj_set_height(ui_eoilpressureback, 60);
    lv_obj_set_x(ui_eoilpressureback, 0);
    lv_obj_set_y(ui_eoilpressureback, 150);
    lv_obj_set_align(ui_eoilpressureback, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_eoilpressureback, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_eoilpressureback, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_oilpressuredu = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_oilpressuredu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_oilpressuredu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_oilpressuredu, 0);
    lv_obj_set_y(ui_oilpressuredu, 90);
    lv_obj_set_align(ui_oilpressuredu, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_oilpressuredu, "Pres kPa");
    lv_obj_set_style_text_font(ui_oilpressuredu, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_eoilpressure = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_eoilpressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_eoilpressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_eoilpressure, -50);
    lv_obj_set_y(ui_eoilpressure, 150);
    lv_obj_set_align(ui_eoilpressure, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_eoilpressure, "1234");
    lv_obj_set_style_text_font(ui_eoilpressure, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}